engines/grim/bitmap.cpp
engines/grim/emi/costume/emichore.cpp
engines/grim/emi/costume/emichore.h
engines/grim/emi/lua_v2.cpp
engines/grim/gfx_base.cpp
engines/grim/gfx_opengl.cpp
engines/grim/gfx_opengl_shaders.cpp
engines/grim/gfx_tinygl.cpp
engines/grim/lab.cpp
engines/grim/lua/liolib.cpp
engines/grim/resource.cpp
math/matrix.h

This patch set contains some bug fixes:
- memleaks reported by valgrind
- non-matching memory allocation/deallocation calls
- minor cleanup
These patches shouldn't cause any functional changes.

Minor bug fixes

---

engines/grim/patchr.cpp

This changes the unsafe pointer reads/writes to use READ_UINT32() / WRITE_UINT32().
Since there are no 64-bit versions of these functions, the 64-bit codepath was eliminated.
I don't know how big the performance gains here are for splitting this into 4-byte chunks, the code would definitely be more readable if it were changed into a simple 1-byte xor...

GRIM: Make patch file reads alignment safe

---

engines/grim/gfx_opengl_shaders.cpp

Fix primitives rendering with TinyGL and Shaders.

Primitives

---

engines/grim/gfx_opengl_shaders.cpp
engines/grim/shaders/emi_actor.vertex
engines/grim/shaders/grim_background.fragment

Remove some unused shader uniform variables.

GRAPHICS: Remove unused shader uniform variables

---

video/mpegps_decoder.cpp

This fixes the build with MAD disabled.
I have not been able to test this, since I don't have PS2 EMI.

VIDEO: Adapt the PS2 MPEG audio track to the new packet stream API

---

engines/stark/formats/iss.cpp

16 bits raw little-endian format used in 4 files in (at least) the GOG
version:
1b/00/xarc/00000100.ssn
1b/00/xarc/01000100.ssn
1c/00/xarc/0000000a01.ssn
1c/00/xarc/0100000a01.ssn

STARK: Add support for "Sound" codec.

---

graphics/tinygl/init.cpp
graphics/tinygl/light.cpp

Discrepancies found while reading opengl docs along with tinygl implementation.

Tinygl opengl compliance

---

engines/grim/gfx_tinygl.cpp
graphics/tinygl/matrix.cpp
graphics/tinygl/vertex.cpp

Try 2, I figured out the extra bit I needed (2nd commit).

Tinygl texture matrix

---

graphics/tinygl/clip.cpp

Based on comment by @bgK in #1265 .

TINYGL: Simplify a bit updateTmp .

---

engines/grim/detection.cpp
engines/grim/grim.cpp

Description borrowed from README.

GRIM, EMI: Expose show_fps in engine options tab.

---

graphics/tinygl/api.cpp
graphics/tinygl/zbuffer.cpp
graphics/tinygl/zbuffer.h
graphics/tinygl/zdirtyrect.cpp

An assortment of unrelated small changes in TinyGL done while browsing the code. I believe it generally improves tinygl, but each change is too small (ie, I did not look for other occurrences of the same issue) for individual pull requests.

Tinygl janitorial

---

graphics/tinygl/zbuffer.cpp

It is possible to convert calls to memset_{s,l} into call to memset when
all bytes of the depth or color value are the same (which is the likely
case), improving buffer clearing speed.
For reference, I developped this to allow adding support for 32bits rendering in TinyGL, but is a stand-alone change.

TINYGL: Avoid calling memset_{s,l} when possible.

---

graphics/tinygl/ztriangle.cpp

Some loops are written in a way which suggests loop-unrolling was intended, but code was re-rolled. This change unrolls these loops.
Note: I did not see any obvious performance difference. If anything, this makes reading the code easier by reducing repetitions, and maybe fixing tiny (runs of 3 pixels) rendering approximations.
This brings #1270 changes because of conflicts.

TINYGL: reduce code duplication in ztriangles (was: [RFC] TINYGL: unroll some loops)

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
graphics/tinygl/ztriangle.cpp

TinyGL is now looking nice, with smooth color transitions.
I did not notice a cpu usage increase. Actually, as there are fewer shift/mask operations I would actually expect a (very) tiny speedup.

Tinygl 32bits

---

graphics/tinygl/init.cpp
graphics/tinygl/vertex.cpp
graphics/tinygl/zblit.cpp
graphics/tinygl/zblit.h
graphics/tinygl/zbuffer.cpp
graphics/tinygl/zdirtyrect.cpp
graphics/tinygl/zdirtyrect.h
graphics/tinygl/zgl.h

More issues found by valgrind while working on dirty rectangles.
Also, contains a better implementation of texture/image cleanup (previous attempt was rejected in #1275 ).

Tinygl memory

---

common/endian.h
engines/grim/bitmap.cpp
engines/grim/emi/animationemi.cpp
engines/grim/emi/costumeemi.cpp
engines/grim/emi/modelemi.cpp
engines/grim/keyframe.cpp
engines/grim/model.cpp
engines/grim/sector.cpp
engines/grim/set.cpp
engines/grim/sprite.cpp
math/quat.h
math/vector.h
math/vector3d.h
math/vector4d.h

Also, rename function to be more consistent with others from common/endian.h .

Fix gcc warnings in get_float on big-endian (take 2)

---

engines/stark/gfx/opengls.h
engines/stark/resources/anim.h
engines/stark/resources/image.h
engines/stark/services/userinterface.h
engines/stark/visual/actor.h

Fix warnings detected by Jenkins

STARK: Fix all stark engine gcc warnings

---

engines/stark/ui/menu/mainmenu.cpp

Related to issue https://github.com/residualvm/residualvm/issues/1419

STARK: Provide loading in the main menu

---

engines/stark/console.cpp
engines/stark/module.mk
engines/stark/resources/location.cpp
engines/stark/resources/location.h
engines/stark/services/diary.cpp
engines/stark/services/diary.h
engines/stark/services/gamechapter.cpp
engines/stark/services/gamechapter.h
engines/stark/services/global.cpp
engines/stark/services/userinterface.cpp
engines/stark/services/userinterface.h
engines/stark/stark.h
engines/stark/ui/menu/dialogmenu.cpp
engines/stark/ui/menu/dialogmenu.h
engines/stark/ui/menu/diaryindex.cpp
engines/stark/ui/menu/fmvmenu.cpp
engines/stark/ui/menu/locationscreen.cpp
engines/stark/ui/menu/locationscreen.h
engines/stark/ui/screen.h

Fix issue #1430 #1431 #1432 #1435 
This PR is opened early to include a link in my GSoC blog. Currently, this branch is based on the unmerged branch-dialog. After merging branch-dialog to master, this branch will be rebased and history will be cleaned. More details will be added after that.

STARK: Improve the debug console

---

engines/myst3/cursor.cpp

Added some comments and made a loop use the size
rather than hardcoded number.

MYST3: Minor cursor refactoring

---

engines/stark/ui/menu/locationscreen.cpp
engines/stark/ui/menu/mainmenu.cpp

STARK: Issue fixing

---

engines/stark/console.cpp

Fixed the changechapter problem

---

engines/stark/services/gamechapter.cpp
engines/stark/services/gamechapter.h

STARK: Add range checking in acquiring chapters' titles and subtitles

---

backends/platform/android/android.cpp
backends/platform/android/android.mk
backends/platform/android/jni.cpp
backends/platform/android/org/residualvm/residualvm/ResidualVMActivity.java
configure
ports.mk

This is partially based on scummvm/scummvm#1278 with some additional ResidualVM-specific changes.

ANDROID: Update to compile with modern NDKs

---

backends/platform/android/events.cpp
backends/platform/android/events.h
backends/platform/android/org/residualvm/residualvm/MouseHelper.java
backends/platform/android/org/residualvm/residualvm/ResidualVMActivity.java
backends/platform/android/org/residualvm/residualvm/ResidualVMEvents.java

ANDROID: Mouse and stylus support

---

.travis.yml
.travis/build-android-deps.sh
.travis/deploy.sh
.travis/freetype-config
configure

As requested in #1553, this is just the Travis changes for building (and optionally deploying) automatically. It will not do anything by itself, Travis needs to be enabled for the repository.

BUILD: Write travis file for Ubuntu, OSX, Windows and Android

---

configure

CONFIGURE: Fix typo in comment

---

backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.h

See also the forums thread for further information
https://forums.residualvm.org/viewtopic.php?f=1&t=766

GRAPHICS: Do not use SDL_WINDOW_RESIZEABLE

---

po/POTFILES
po/module.mk

This PR fixes an oversight in the code for merging po files.
With this on top of the branch in #1540, I have a fully translated ResidualVM

I18N: Properly merge ResidualVM .po files

---

backends/graphics/openglsdl/openglsdl-graphics.cpp

Solution taken from Supertux: https://github.com/SuperTux/supertux/pull/808

Fix error during glew loading under Wayland

---

backends/graphics/sdl/resvm-sdl-graphics.cpp
backends/graphics/sdl/resvm-sdl-graphics.h
backends/platform/sdl/sdl-window.cpp
backends/platform/sdl/sdl-window.h
backends/platform/sdl/sdl.cpp
backends/platform/sdl/sdl.h

See also scummvm/scummvm#2191.

SDL: Move detection of the desktop resolution into the SdlWindow class

---

README.md
backends/platform/sdl/riscos/riscos.mk
dists/riscos/!Help,feb
dists/riscos/!Run,feb
dists/riscos/FindHelp,fd1
dists/riscos/manual/stronghelp.lua

This is a rebased version of PR #1616 that contains changes to the packaging that weren't updated in commit b586571.

RISCOS: Apply additional fixes from ScummVM

---

engines/icb/cluster_manager_pc.cpp
engines/icb/common/px_windows.h
engines/icb/res_man_pc.cpp

There were 2 different issues:
- A problem in the scope of an `#if`-`#endif` code block
- A problem with include orders

ICB: Fix windows build

---

engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.cpp
engines/wintermute/base/gfx/opengl/shaders/sprite.vertex

GSOC WME3D: Display transformed sprites fixes
