residualvm/residualvm

- engines/grim/resource.cpp
- engines/grim/resource.h
Commit 2e7b6a0ec1d825526dc10cee17efd31dc8591c24 introduced the problem that _options.lua from local.m4b took precedence over _options.lua from patch.m4b in EMI.
That caused the problem that the patch from residualvm-emi-patch.m4b never got applied and so the game's integration into the preference handling of the engine was turned off (system_prefs.loadprefs was not overwritten with residualvm's version).
This patch fixes the problem by reverting some portions of the original commit but still avoids the problem that local.m4b is opened multiple times (which is very slow on on Mac).
> EMI: Fix caching of local.m4b

- engines/grim/grim.cpp
- if luaUpdate() is called more than once during the same millisecond
then delay the next call by one millisecond
- this avoids the issue that _frameTime is set to 0 which would
cause getPerSecond() to return 0 for any given rate
- if getPerSecond() returns 0 then that would cause dist to be 0 in walkForward() which would cause the walk animation to stop (even if the actor is supposed to keep walking)
- if that happens, e.g. Guybrush would walk quite erratically
> GRIM/EMI: Limit frequency of luaUpdate()

- README.md
- backends/events/sdl/resvm-sdl-events.cpp
- backends/events/sdl/resvm-sdl-events.h
- backends/module.mk
- backends/platform/sdl/sdl.cpp
- common/events.h
- engines/grim/grim.cpp
- engines/grim/grim.h
- engines/grim/grim_controls.cpp
This commit adds true joystick/gamepad support to the Grim/Emi engine. I have rebased the commits from #721 and made some minor modifications (comments, support for EMI, ...).
As inherited from ScummVM, the joystick support has to be enabled globally either with the "--joystick" command line option or by adding "joystick_num=0" to the [residualvm] section of ~/.residualvmrc.
Tested with X-Box 360 controller in EMI and GRIM.
> GRIM/EMI: Add Joystick/gamepad support

- engines/grim/sector.cpp
- fixes a path finding issue (#992)
> EMI: Relax height check for bridges between sectors

- engines/grim/bitmap.cpp
- engines/grim/gfx_opengl_shaders.cpp
- engines/grim/gfx_tinygl.cpp
Add some nullptr checks to avoid segfaults on cleanup.vu
> GRIM/EMI: Add nullptr checks to avoid segfaults on cleanup

- engines/grim/md5check.cpp
These are the verified, correct checksums for most german disc versions
(after removal of the "copy protection" that is on some discs).
Please the the original MD5 forum thread for verification: http://forums.residualvm.org/viewtopic.php?t=215 - Here user desperadoduck, M[u]ddy and mark verify those MD5 sums as correct
Additionally, I can confirm those MD5 sums match with my own version. See also #796, where I try to explain how those incorrect MD5s ended up in the source code (probably a copy & paste error).
> GRIM: Fix MD5 sums for german versions.

- engines/grim/movie/codecs/codec48.cpp
This PR fixes a bunch of compile warnings of the following type:
<pre>warning: cast from type ‘const byte* {aka const unsigned char*}’ to type ‘uint32* {aka unsigned int*}’ casts away qualifiers [-Wcast-qual]</pre>
> GRIM: Fix compile warnings in codec48.cpp

- engines/grim/detection.cpp
- engines/grim/emi/lua_v2.cpp
- engines/grim/grim.cpp
- engines/grim/lua_v1.cpp
Change the memory card id and the reported free space so that the game is able to save.
There are some remaining issues:
* When finished loading a game, the game displays “Save Successful.” This seems to be just a visual bug.
* The game saves without *.gsv file extensions, resulting in filenames such as “efmi000”.  This prevents loading one of these saves from ResidualVM’s menus.
* Save thumbnails are displayed incorrectly.
> EMI: Allow saving in-game on the PS2 version

- engines/grim/actor.cpp
- engines/grim/actor.h
- engines/grim/emi/costumeemi.cpp
- engines/grim/emi/costumeemi.h
- engines/grim/emi/lua_v2_actor.cpp
- engines/grim/emi/modelemi.cpp
- engines/grim/emi/modelemi.h
- engines/grim/gfx_opengl.cpp
- engines/grim/gfx_opengl_shaders.cpp
- engines/grim/gfx_tinygl.cpp
- engines/grim/shaders/emi_actor.fragment
* if Lua_V2::SetActorGlobalAlpha() is called with a mesh name,
set a mesh-specific alpha value / mode
* use this alpha value in drawEMIModelFace()
* this commit fixes the problem that the whole actor vanishs in some scenes
* issue #896: when entering or leaving the porch of the of LUA bar 
* issue #1151: when jumping out/in the bank window)
* instead of fading the actor in or out, only his shadow is faded correctly
* implemented for all 3 graphic drivers
> EMI: Implement mesh-specific alpha values

- dists/xcode/residualvm.xcodeproj/project.pbxproj
Add codec48.cpp, quicktime.cpp and resvm-sdl-events.cpp to the Xcode project so that it compiles without linker errors. Also add their respective header files.
> XCODE: Add missing files to the Xcode project

- engines/grim/gfx_opengl_shaders.cpp
With OpenGL the created textures were mirrored in y direction
because OpenGL uses a different coordinate system where (0, 0)
is the bottom left corner.
This fixes the problem that the savegame screenshots are upside-down when using the OpenGLS renderer.
> EMI: Flip y coordinate when creating screenshot textures

- engines/grim/gfx_opengl_shaders.cpp
- engines/grim/shaders/emi_actor.vertex
- engines/grim/shaders/grim_actor.vertex
This patch set enables lighting code in actor vertex shader.
This is my first stab at shaders, so please carefully review and tell me what I'm doing wrong.
I tried to change as little CPU as possible, because I'm afraid of all the special-casing for GRIM vs. EMI.
I did move attenuation computation to shader, though, which required me to update EMI shader. Was this a good idea ? My idea is that shader needs to multiply color with per-vertex intensity anyway, so rather than starting at intensity 1.0 and reducing it with normal-to-light, distance and cone attenuation, I should be able to just start at intensity and do the same for the same cost. I also tried to code the shader defensively whenever a divide-by-zero is possible, although I would tend to trust game data.
> RFC Enable GRIM glsl lighting

- engines/grim/emi/modelemi.h
- engines/grim/gfx_opengl.cpp
- engines/grim/gfx_opengl_shaders.cpp
- engines/grim/gfx_tinygl.cpp
Use bit 0x20 in the mesh face flags to disable ligthing. This fixes the problem that once a previous screen is used as texture (e.g. in the intro or for the transition effects in set kab when walking eastwards or westwards), it is shown too dark due to the applied static lighting for overworld actors. When drawing the according faces for these actors, lighting should be disabled.
This commit fixes issue #1045.
Additionally, it fixes the same problem in the intro: the transition effects are too dark, too.
Note: using bit 0x20 is just a guess, but this bit is distinctive for the affected costumes/meshes. Alternatively, we could just use "kUnknownBlend" bit which would also fit.
> EMI: Check bit in mesh face flags to disable lighting

- engines/grim/gfx_opengl_shaders.cpp
Since commit 1908a43d189cc030753e0ec2e7654fb5c09e442b _spriteProgram was not a clone of _actorProgram in engines/grim/gfx_opengl_shaders.cpp anymore.
Because of that both shader programs did not share the uniforms anymore. Since not all necessary uniform variables were set for _spriteProgram (in case of the "emi_actor" shader), the mentioned patch cause a regression:
- the sprites (e.g. background of menu, clock and compass in the swamp) were missing for OpenGLS in EMI
This patch fixes the problem by setting the necessary uniforms in startActorDraw() for _spriteProgram, too.
> RFC: Set uniform parameters for _spriteProgram

- engines/grim/bitmap.cpp
- engines/grim/emi/emi.cpp
- engines/grim/emi/emi.h
- engines/grim/emi/layer.h
- engines/grim/emi/lua_v2.cpp
- engines/grim/gfx_opengl.cpp
- engines/grim/gfx_opengl_shaders.cpp
- engines/grim/gfx_tinygl.cpp
This patch set enables the drawing of layers which are dynamically created by EMI's lua code.
* enables the illumination of the neon signs of Planet Threepwood on Jambalaya Island
* turns on water effects in the lagoon on Lucre Island
* hides the cannonball on the beach of Knuttin Atoll until it is actually landed (issue #1046)
> Implement drawing of dynamically created layers

- engines/grim/emi/emi.cpp
Instead of just ordering the textobjects by their layer, use their
creation time (indirectly provided by the pool ID which is continuously
counting up).
This ensures that if there are multiple textobjects with the same text
ID and the same layer, that the latest is drawn last and overwrites the
previous ones.
That's necessary since the LUA code will create multiple instances of
the same textobject for the color fading effect in the credits.
This fixes the issue #1155.
> EMI: Correct draw order of textobjects

- engines/grim/bitmap.cpp
- engines/grim/bitmap.h
- engines/grim/emi/layer.cpp
- engines/grim/gfx_opengl.cpp
- engines/grim/gfx_opengl_shaders.cpp
- engines/grim/gfx_tinygl.cpp
This patch makes sure, that Layer::_frame is smaller than numLayers
of the bitmap in order to prevent out-of-bounds access to
BitmapData::_layers.
This fixes a crash when finding the secret hideout: #1195.
> EMI: Fix wrap around of Layers/Frames

- engines/grim/emi/costume/emianim_component.cpp
This fixes the problem if the costume uses only key 3 ("Loop") but not
key 1 ("Play") for an animation. This happens e.g. for Pegnose's "run" chore (issue #1169).
> EMI: Start animation when "Loop" key is set

- engines/grim/emi/animationemi.cpp
- engines/grim/emi/animationemi.h
Both the animation components/tracks and the chores itself keep track of
the current time independently:
animation component:
- AnimationStateEmi::_time
- initialized with 0
- after the first update() call, _time is advanced by the frametime
chores:
- Costume::_currTime
- initialized with -1
- during the first update() call, _currTime is set first to 0
- during the next update() call, _currTime is advanced by the frametime
EMICostume::update() updates first the chore and then all components
with the same frame time. This has the effect, that the internal time
base of the chore and the animation has always an initial offset (the
value of the frametime of the first update() call).
For some costumes, the chore will pause the animation by setting the
according key for that animation at the …
> EMI: Keep time of chores and animations in sync

- devtools/create_project/config.h
- devtools/create_project/msbuild.cpp
- devtools/create_project/visualstudio.cpp
Since all our projects use OpenGL, we always need language extensions to be enabled.
My motivation here is that I can have one build of create_project that I don't need to update when new engines are in development.
> DEVTOOLS: Allways enable langauge extentions for MSVC

- math/line3d.cpp
It was previously doing a line vs line segment intersection test
I'm a bit confused with this class. It is named Line3d, but actually is a line segment.
I'm also unsure about that change, perhaps the line vs line segment intersection was what was intended.
I tested Grim a bit without noticing any regression.
> MATH: Fix Line3d::intersectLine2d to do a line segment intersection test

- configure
- engines/grim/POTFILES
- engines/grim/grim.cpp
- engines/grim/md5check.cpp
- engines/grim/md5checkdialog.cpp
- engines/grim/resource.cpp
- engines/myst3/POTFILES
- po/POTFILES
- po/module.mk
- po/msgcut
- po/residualvm/README
- po/residualvm/nl_NL.po
This PR is a suggested fix for #1206.
It enables us to inherit translations from ScummVM where they match (mostly the launcher), and add our own translations (currently the md5 checkers and the "patch needed" dialogs).
I have included a sample translation for the `nl_NL` locale to illustrate.
> TRANSLATION: Support for both (ScummVM) inherited and (ResidualVM) new translations

- po/de_DE.po
- po/residualvm/de_DE.po
This adds a German translation file (de_DE.po) that includes all ResidualVM-specific stuff to ResidualVM.
All strings are translated, but unfortunately, I'm currently unable to build a working translations.dat - the changes I made in /po/residualvm/de_DE.po are not included in /po/de_DE.po and therefore not build into translations.dat.
I followed all instructions in /po/residualvm/README, but without luck - the /po/de_DE.po file always contains the untranslated strings and ignores the translated strings in /po/residualvm/de_DE.po
Best regards
rootfather
> I18N: Add German translation for ResidualVM-specific strings

- engines/grim/gfx_opengl.cpp
- engines/grim/gfx_opengl_shaders.cpp
- engines/grim/gfx_tinygl.cpp
- engines/grim/set.cpp
- engines/grim/set.h
Low-hanging fruits I found while working on lighting last year, where computation could be obviously moved to less-called code.
I do not remember formally benchmarking the difference. Feel free to reject.
> Move computations out of renderer

- dists/residualvm.rc
- dists/residualvm.rc.in
Our users are used to ResidualVM's executable not to require extra files, as can be seen there http://forums.residualvm.org/viewtopic.php?f=1&t=712. This embeds the shaders files in the Windows executable.
I'm not happy with having to list all the shaders in the .rc file, but can't think of a better solution. Putting the shaders in some kind of archive would be nice. But I don't know if it can be done easily when building with Visual Studio.
This was not tested with Visual Studio.
> WIN32: Embed the shaders in the executable

- backends/graphics/surfacesdl/surfacesdl-graphics.cpp
- backends/graphics/surfacesdl/surfacesdl-graphics.h
Introduce a GameRenderTarget enumeration defining how the game is rendered
on the screen: directly, using a sub-surface, or using a framebuffer.
Split the video initialisation code into simpler methods.
The logic should be exactly the same as before.
The underlying goal is to hopefully make it easier to port that portion to SDL2 in the future.
> SDL: Reorganize the game render target selection code

- engines/stark/detection.cpp
These are the hashes of the original German retail version.
> STARK: Add support for German TLJ 4CD version

- backends/graphics/surfacesdl/surfacesdl-graphics.cpp
- backends/graphics/surfacesdl/surfacesdl-graphics.h
- graphics/opengl/context.cpp
- graphics/opengl/context.h
- graphics/opengl/framebuffer.cpp
- graphics/opengl/framebuffer.h
- graphics/opengl/system_headers.h
The Grim engine draws to a framebuffer, when used in fullscreen mode, in order to use the desktop resolution and scale keeping a correct aspect ratio. This is an updated version of @Botje's work on enabling anti-aliasing when rendering to framebuffers (#1191).
I have added error checking and fallbacks to Botje's work, so that it should be in a mergable state.
> Multisampling for framebuffers

- backends/graphics/surfacesdl/surfacesdl-graphics.cpp
- backends/graphics/surfacesdl/surfacesdl-graphics.h
- backends/platform/sdl/sdl-sys.h
This PR contains minimal changes to make ResidualVM work with SDL2. It is based on previous work by @aquadran and the ScummVM team.
Features are the same as with SDL1. The only exception being that it is now possible to use GLES2 contexts when building with SDL2.
Configuring with SDL2 is done using the following command:
`SDL_CONFIG=sdl2-config ./configure`
Configuring with SDL2 for GLES2 is done using the following command:
`SDL_CONFIG=sdl2-config ./configure --force-opengles2 --disable-glew --enable-opengl-shaders`
This command looks like a black magic invocation, and should probably be simplified at a later point.
I've done tests without noticing bugs in the following configurations:
- Linux OpenGL (mesa/radeonsi)
- Linux GLES2 (mesa/radeonsi)
- Windows 7 OpenGL (AMD Catalyst)
- …
> Basic port to SDL2

- engines/grim/actor.cpp
- engines/grim/costume.cpp
- engines/grim/costume.h
- engines/grim/costume/component.h
This method is never implemented, so drop its declaration and callers.
> GRIM,EMI: Drop Grim::Component::setupTexture

- engines/grim/gfx_opengl_shaders.cpp
- engines/grim/shaders/grim_actor.vertex
Fixes appearance of roulettes in cn and beavers in dm (#1186).
> GRIM, SHADERS: Toggle light inside drawMesh.

- backends/graphics/graphics.h
- backends/graphics/openglsdl/openglsdl-graphics.cpp
- backends/graphics/openglsdl/openglsdl-graphics.h
- backends/graphics/sdl/resvm-sdl-graphics.cpp
- backends/graphics/sdl/resvm-sdl-graphics.h
- backends/graphics/surfacesdl/surfacesdl-graphics.cpp
- backends/graphics/surfacesdl/surfacesdl-graphics.h
- backends/modular-backend.cpp
- backends/modular-backend.h
- backends/module.mk
- backends/platform/sdl/sdl.cpp
- backends/platform/sdl/sdl.h
- graphics/module.mk
- graphics/opengl/surfacerenderer.cpp
- graphics/opengl/surfacerenderer.h
- graphics/opengl/tiledsurface.cpp
- graphics/opengl/tiledsurface.h
The general goal for these changes is to move the OpenGL specific code out of SurfaceSdlGraphicsManager so that the code is less messy, and it is easier to add features. Possibly in the future the OpenGL code could be further separated from the SDL code so that it can be reused for other platforms.
A new class, ResVMSdlGraphicsManager has been added in the class hierarchy between SurfaceSdlGraphicsManager and SdlGraphicsManager to be able to share common code between the surface and OpenGL graphics managers. The OpenGL code has been moved to OpenGLSdlGraphicsManager, subclassing ResVMSdlGraphicsManager.
The SDL platform code now chooses to instantiate either SurfaceSdlGraphicsManager or OpenGLSdlGraphicsManager based on the "accel3d" parameter of the "setupScreen" method.
The OpenGL code …
> SDL: Split the OpenGL code to a separate GraphicsManager

- engines/grim/gfx_tinygl.cpp
- graphics/tinygl/clip.cpp
- graphics/tinygl/zbuffer.h
- graphics/tinygl/zline.cpp
- graphics/tinygl/ztriangle.cpp
Before the first patch, enabling TGL_ALPHA_TEST in GRIM would cause clipped faces to completely disappear (with a striking effect in set mo when near the tube): their vertices' color would become 0 because of updateTmp saving & restoring W color component while it was never set before. And of course, enabling alpha testing makes these vertices go away along with their textures.
The TinyGL patch corrects this original issue, and the GRIM patch makes use of alpha test.
As a result, alpha textures (like the card) look better than before.
> TinyGL: Fix TGL_ALPHA_TEST support with clipped triangles

- engines/grim/gfx_tinygl.cpp
Forgotten in #1265 . I do not know where this has a visible effect (smoke from Manny's idle animation seemed already alpha-blended with background without this).
> GRIM: Enable TGL_ALPHA_TEST in GfxTinyGL::drawSprite.

- README.md
Some users have difficulties finding/installing that file (as it's a single one and located in the "MonkeyInstall" drawer which never seems to be checked when copying the data over.
> README: Add the easy to miss Local.m4b of EMI

- engines/grim/gfx_tinygl.cpp
Fixes a memory leak when playing videos: each frame would leak as the
previous one does not get reused or freed.
> GRIM: Reuse existing blit image.

- engines/grim/gfx_opengl.cpp
- engines/grim/gfx_tinygl.cpp
- graphics/tinygl/api.cpp
- graphics/tinygl/gl.h
- graphics/tinygl/matrix.cpp
- graphics/tinygl/zdirtyrect.cpp
Two short changes to TinyGL which allow copying OpenGL renderer implementation of these methods over to TinyGL one.
Fixes #1181 .
> GRIM: Fix drawLine/Rect/Polygon in TinyGL renderer

- graphics/tinygl/zbuffer.h
- graphics/tinygl/zline.cpp
drawLine was broken for dx = 0 lines.
Also, the split between fillLineGeneric and drawLine, along with the many
parameters exchanged (with obscure names with subtle differences), made
the code hard to understand.
This implementation should be easier to check.
There was no visible CPU usage change.
Fixes GRIM's ticket printer (#1262 is needed too), which are composed of a lot of vertical
segments.
I am not used to C++, so there may be possible simplifications. For example:
- I split `putPixel` to avoid a "variable may be used before being initialised" warning, although it should be harmless in practice (the 3rd argument would be used in `putPixel` when `kInterpZ` is false anyway).
- I made `putPixel` and `drawLine` into (private) methods rather that static functions because this seems more …
> TINYGL: Simplify zline.cpp .

- engines/grim/gfx_tinygl.cpp
- engines/grim/imuse/imuse_mcmp_mgr.cpp
- engines/grim/imuse/imuse_sndmgr.cpp
- graphics/tinygl/init.cpp
- graphics/tinygl/texture.cpp
- graphics/tinygl/zdirtyrect.cpp
- graphics/tinygl/zgl.h
There are still some errors, but this gets rid of a few tens of megabytes of leaks around textures.
> TINYGL, GRIM: Fix various errors (mostly memory leaks) found by valgrind

- graphics/tinygl/init.cpp
- graphics/tinygl/light.cpp
- graphics/tinygl/zgl.h
Avoids or deffer normalising when possible.
Avoids computing specular when light & material combination would produce no specular effect.
> Tinygl: optimise gl_shade_vertex

- engines/grim/bitmap.h
- engines/grim/grim.cpp
Pixel format does not seem to be stored in save game, so when loading a
save game produced in 32 bits mode it appears corrupted. So, to preserve
backward compatibility, convert to 16bits format before storing.
I guess it would be better to store this inside the savegame, but:
- we need to preserve backward compatibility
- I think forcing 16 bits for the save/load game screenshots is perfectly acceptable
so I do no feel it is worth the effort.
For reference, I developped this to allow adding support for 32bits rendering in TinyGL, but is a stand-alone change.
> GRIM: Convert save game image to original pixel format.

- engines/grim/bitmap.cpp
- engines/grim/gfx_tinygl.cpp
- graphics/tinygl/zblit.cpp
So caller does not have to depend on the pixel format used internally to
BlitImage.
Update callers which do request for color keying (GRIM/EMI only).
Also, remove a special-casing of transparent color when converting image
format which sets a color in a packed format independent from actual
destination format.
Also, in GfxTinyGL::createTextObject, prefer changing invisible colorKey
value than actually-visible color.
This commit is larger than I would like it to be, but involved parts are quite entangled - and this is precisely what this commit tries to address.
For reference, I developped this to allow adding support for 32bits rendering in TinyGL, but is a stand-alone change.
> TINYGL: Expect colorKey in the same pixel format as surface.

- graphics/pixelbuffer.cpp
- graphics/pixelbuffer.h
Avoid doing a lot of operations just to move 2 or 4 bytes around.
> GRAPHICS: Optimise PixelBuffer::getValueAt and PixelBuffer::setPixelAt.

- graphics/tinygl/zbuffer.h
- graphics/tinygl/zline.cpp
- graphics/tinygl/ztriangle.cpp
And avoid calling it altogether when possible.
Note: contains #1266 as it would otherwise conflict, I don't know how to do otherwise to still propose these patches.
> Tinygl: optimise scissorpixel

- graphics/tinygl/zbuffer.cpp
This method is used to blit large buffers, so a large unrolling is still
beneficial. As it is the second hottest-spot in grim, the frame rate
increase is most significant there (compared to emi).
I left the `// TODO: could be faster, probably.` comment as this method is still rather costly.
> TINYGL: Unroll FrameBuffer::blitOffscreenBuffer.

- engines/grim/material.cpp
- engines/grim/material.h
Implementing some understanding I had of material file structure while working no lighting code last year.
Very few material files define their own color maps:
DATA000.LAB/blue.mat
DATA000.LAB/orange.mat
DATA000.LAB/pink.mat
DATA000.LAB/white.mat
DATA001.LAB/bren_chest.mat
DATA001.LAB/bren_shin.mat
DATA001.LAB/bren_skin.mat
DATA001.LAB/bren_thigh.mat
DATA004.LAB/bren_chest.mat
DATA004.LAB/bren_shin.mat
DATA004.LAB/bren_skin.mat
DATA004.LAB/bren_thigh.mat
Also, walk (but ignore) downscaled mipmaps. Even fewer files contain them, and
they contain a single image each (with 3 mipmaps):
DATA000.LAB/dflt.mat
DATA000.LAB/shadow.mat
> GRIM: Adds support for loading embedded colormaps.

- engines/grim/material.cpp
- engines/grim/material.h
Reverts residualvm/residualvm#1221
> Revert "GRIM: Adds support for loading embedded colormaps."

- engines/grim/gfx_tinygl.cpp
For some reason blending happens in RGB565 even without blend enabled.
> GRIM: Enable blending around Graphics::tglBlit calls

- graphics/tinygl/zbuffer.cpp
- graphics/tinygl/zbuffer.h
- graphics/tinygl/ztriangle.cpp
Two fixes (hidden glitch & tiny performance improvement) for earlier merged commits, plus several simplifications found while working on dirty rectangles and texture formats.
> Tinygl simplify ztriangle

- engines/grim/gfx_opengl.cpp
- engines/grim/gfx_opengl_shaders.cpp
- engines/grim/gfx_opengl_shaders.h
- engines/grim/shaders/smush.fragment
Make shader renderer fail the same way as opengl renderer on unexpected pixel format, which also allows getting rid of the "swizzle" uniform by letting opengl handle it ( @Botje : please confirm there was no other intent, like maybe some android workaround).
Add support for RGBA REV pixel format, so opengl and shader renderers do not fail as reported in #1300 .
Also, request quicktime high-color videos to use the 8/16/24 pixel format (untested as I could not identify a quicktime video in the EMI EN demo linked from residualvm website).
Patch set tested against:
- shaders + grim-win-fr (intro video is RGB, so it's a different code path anyway)
- shaders + monkey4-win-fr (sinking ship & arrival on melee videos are RGBA REV, hitting the new code path)
- opengl + monkey4-win-fr (likewise)
- …
> GRIM: Fix support for reverse-order 32bits video frames in OpenGL

- engines/engine.h
- engines/grim/grim.cpp
- engines/grim/grim.h
- engines/grim/lua/ltm.cpp
In the grim engine, ResidualVM's Global Game Menu is overridden to show the game menu instead. Now that ResidualVM supports several games, I think that the GMM override is no longer justified.
This re-enables the GMM, allowing to return to the launcher and start another game.
> GRIM: Enable the Global Game Menu

- engines/stark/resources/command.cpp
- engines/stark/resources/command.h
- engines/stark/resources/layer.cpp
- engines/stark/resources/layer.h
- engines/stark/resources/location.cpp
- engines/stark/resources/location.h
Implementation of opRumble based on the original version. I have 2 questions here:
- @bgK mentioned in #1305 that the random values are between -1 and 1. Am I missing something here, I can only see offset in each axis of either -1 or 0 and restoring in the end?
- Rumbling is still quite fast in a visual comparison. This seems down to the value of millisecondsPerGameLoop, which I think is set in w_module.dll(0x10029372) to a static value of 33? Is it worth either increasing our mainLoop delayMillis call or something more complicated in updateDisplayScene?
> STARK: Add support for opRumble

- dists/macosx/Info.plist
- dists/macosx/Info.plist.in
This was removed, I assume by mistake, in commit 9ba9c69b that sync'ed
the code with ScummVM.
> BUILD: Add back icon for MacOS X bundle

- backends/platform/android/org/residualvm/residualvm/ResidualVM.java
- backends/platform/android/org/residualvm/residualvm/ResidualVMActivity.java
These make ResidualVM crash on application initialisation.
Note: this alone is merely enough to get residualvm to start. There are many issues after that:
- adding a game, as of android 7, is impossible as / is "empty", so once there user cannot go down in filesystem tree. Hacked to force /storage/ initial path (not in this PR).
- upon adding a game it crashes because configuration parser somehow finds `vsync=""`, and the emty string is not a boolean (indeed). Hacked parser to return `true` when failing to parse (not in this PR)
- then, shaders are not easily found: they are not copied to the install tree (and makefile does not update that part of the install tree for some reason), and even when shaders are present they are still not found on the device (not sure what made this work, …
> ANDROID: Apply a few missed backports

- graphics/tinygl/arrays.cpp
- graphics/tinygl/gl.h
- graphics/tinygl/opinfo.h
To be used in GRIM iris implementation, avoiding direct framebuffer writes.
> TINYGL: Implement tglDrawArrays.

- engines/grim/actor.cpp
- engines/grim/actor.h
- engines/grim/gfx_base.h
- engines/grim/gfx_tinygl.cpp
- engines/grim/gfx_tinygl.h
- engines/grim/grim.cpp
- engines/grim/lua_v1_graphics.cpp
- engines/grim/savegame.cpp
This should fix #1042 and #1251 .
These were present to implement actor freezing in software rendering mode
in the way original engine was intended for performance reason.
In residualvm, software rendering will generalise the principle through
dirty-rectangles management, so off-screen buffers should not be needed.
Also, properly implementing them requires invasive changes (move previous
draw call list from global OpenGL context to individual off-screen buffers,
along with associated linear vertex allocator, adding a new draw call to
track requested buffer changes until final on-screen frame buffer
presentation).
So instead of such added complexity, lie to lua API about actor not being
in set but keep it in so it is part of normal redraw sequence.
Fixes disappearing actors in cn, bi. …
> GRIM: Drop off-screen buffers

- engines/grim/grim.cpp
Fixes
"Allocator out of memory: couldn't allocate more memory from linear allocator."
error with TinyGL in Grim at the begining of Year 2 after the cinematic
where meche boards the ship. The error only happens when not skipping
the video.
This is an RFC because I am not sure:
- if it is correct at all ? (ie, are their effects beyond just rendering in not calling updateDisplayScene ?)
- if something else should also be done to understand why it takes several frames for flipping to be enabled again after that video (maybe actor rotation is not instant, and if not should it be ?)
- should I also move the _flipEnable test outside of doFlip ?
> GRIM: Do not draw when flipping is forbidden.

- graphics/tinygl/init.cpp
- graphics/tinygl/zdirtyrect.cpp
Once #1295 and #1335 are merged, I believe dirty rectangles can finally be enabled by default ! (this PR contains both, for testing ease)
Actually, I think about getting rid of the non-dirtyrect code paths in TinyGL. Not sure it would be a good idea to include in this PR, though.
I gave up on my attempts to rework rectangle merging algorithm: current code is simple where my code is complex and brittle - and both perform just the same.
There is one part where current code would likely benefit from improvements: using a diff algorithm against draw call lists, instead of current `a++ == b++`-style comparison.
Also, a bit of trivia: on my T450s, TinyGL now give more FPS than OpenGL (i5-4300U 1.9GHz + HD4400), both with same residualvm built with `--enable-optimisations`. Both being in the few …
> TINYGL:  Enable dirtyrect by default.

- backends/graphics/surfacesdl/surfacesdl-graphics.cpp
- base/commandLine.cpp
- engines/grim/gfx_tinygl.cpp
- engines/grim/grim.cpp
- engines/myst3/gfx_tinygl.cpp
Add a --bpp option (0, 16, 32).
Document existing --engine-speed option.
Drop duplicate default option declarations.
Questions for review:
- is "ALL" prefix good here ?
- any idea why command line options only seem to work (from engine point of view) when *not* showing the launcher (ie, starting directly to game is fine) ?
- is it fine to discard duplicate default option declarations ?
/cc @bgK @raziel-
> ALL: Add a --bpp option (and simple command-line patches)

- common/endian.h
I am not famliar enough with C++ to tell whether reinterpret_cast is required here.
At least, disassembling `Grim::EMIModel::loadMesh` (one of the call sites) on ppc32 binary with `--enable-optimizations`, I see this:
```
ed8:       48 00 00 01     bl      ed8 <Grim::EMIModel::loadMesh(Common::SeekableReadStream*)+0x108>
ed8: R_PPC_REL24        Common::String::operator=(Common::String const&)
edc:       89 41 00 48     lbz     r10,72(r1)
ee0:       55 49 c0 3e     rotlwi  r9,r10,24
ee4:       51 49 42 1e     rlwimi  r9,r10,8,8,15
ee8:       51 49 46 3e     rlwimi  r9,r10,8,24,31
eec:       91 21 00 5c     stw     r9,92(r1)
ef0:       3d 20 43 30     lis     r9,17200
ef4:       91 21 00 58     stw     r9,88(r1)
ef8:       81 3f 00 00     lwz     r9,0(r31)
efc:       80 7e 00 90     lwz …
```
> COMMON: Fix gcc warnings in get_float on big-endian

- backends/platform/android/org/residualvm/residualvm/ResidualVM.java
Fixes
rate effect can only handle rates < 131072
error for example when starting grim intro video.
> ANDROID: Limit mixer output sample rate

- engines/grim/gfx_opengl.cpp
It seems that glVertexPointer is not supposed to work with a direct pointer passed in. It does work in every case, other than the intel integrated driver. On windows it crashes and on linux it just doesn't for the frames that make this call.
This was added by @somaen as an optimization, but I think it's more safe to just revert it so we don't cause crashes.
This (probably, I can't get my laptop to stop using the nvidia driver) fixes #1377 and maybe #723 and #720.
> GRIM: Switch iris renderer to regular rendering

- engines/myst3/detection.cpp
- engines/myst3/subtitles.cpp
Hi,
I added a checksum for the Polish version of Myst 3 (4 CD Play-It version, it's actually dual-language) and fixed encoding of the subtitles (which also eliminates crashes). This version is not using windows-1250 encoding but rather a MacOS Central European one.
Some images:
[Subtitles before encoding fix](https://gs.smuglo.li/file/49c43f3c615e5117bc72851b6e4b0cbc1c58e2a44e7587ad3bf5cd97c64a3781.png)
[Subtitles leading to crashes](https://gs.smuglo.li/file/9dd6a2f8cee8f2e4761dbede9a85406a5ec23675806c4212174005b0ac9e1c40.png)
[With fixed encoding](https://gs.smuglo.li/file/9efb1940aecf4b3ad5cc815ff9151634a94189711882a1ce2872fcc58eb7e950.png)
> MYST3: fix Polish version detection and subtitles

- engines/grim/costume/model_component.cpp
- engines/grim/model.cpp
- engines/grim/model.h
Most graphics cards limit us to a stack size of 32. In some places
like the pigeons on the roof of the DOD, they will render too many
matricies pushed to the stack.
If we don't need to push it to the stack, skip pushing.
Creating this as a PR hoping someone will check my logic.
> GRIM: Cut back on the number of glPushMatrix operations

- engines/stark/resources/item.cpp
There was not proper text hints in some scenes for objects and background because of wrong index.
> STARK: Fix not matching mouse hints

- backends/graphics/openglsdl/openglsdl-graphics.cpp
- graphics/opengl/context.cpp
- graphics/opengl/context.h
- graphics/opengl/framebuffer.cpp
Raspberry PI doesn't support 16 depth framebuffer. This patch uses 24 when capable (16 if not).
This resolve the problem and allow to run ResidualVM fullscreen on RPI platforms (with 3D acceleration).
> Support fullscreen on RPI (using framebuffer)

- engines/stark/services/userinterface.cpp
- engines/stark/ui/menu/diaryindex.cpp
- engines/stark/ui/menu/diaryindex.h
- engines/stark/ui/menu/locationscreen.cpp
- engines/stark/ui/menu/locationscreen.h
- engines/stark/visual/text.cpp
- engines/stark/visual/text.h
Fix the issue #1402.
I want to change as less code as possible, which was a little bit hard since all the functions related to resetting text texture are encapsulated, so I did in an indirect way. I "forced" the render entry to reset the texture by changing the text color to another and then change it back. Also I had to add a function on StaticLocationWidget to check whether it is safe to call the setTextColor function.
Honestly all these are not that ideal from my perspective. It would be a lot more elegant if I can add some other functions or use friend function, but I am afraid that this will violate the original encapsulation.
> STARK: Fixing the text resized problem on diary index menu

- engines/stark/ui/world/fmvscreen.cpp
- engines/stark/ui/world/fmvscreen.h
Related to https://github.com/residualvm/residualvm/issues/1423
When the *High Quality Videos* setting is unchecked but the low-resolution video cannot be found, the original high-resolution video, if it exists, will be played instead.
This is done in case some versions of TLJ have inconsistent videos.
> STARK: Use high-res video when low-res is not available

- engines/stark/console.cpp
* Removed full stops from the last setence in `debugPrintf`s to unifty the style
* `dump` folder for `dumpArchive` must exist in location ResidualVM is launched from (e.g. $HOMEDIR)
* `dumpArchive` require not only name of the archive but (relative) path to it, e.g. `4f/04/04.xarc` instead of simply `04.xarc`
* Indicated to use `listInventory`  to get ids for `enableInventoryItem`
* `enableInventoryItem` incorrectly had description from `changeLocation`
* Indicated to use `listLocations`  to get ids for `changeLocation`
> STARK: Updated descriptions of some debug commands

- engines/stark/module.mk
- engines/stark/savemetadata.cpp
- engines/stark/savemetadata.h
- engines/stark/services/gamechapter.cpp
- engines/stark/services/gamechapter.h
- engines/stark/services/services.h
- engines/stark/services/settings.cpp
- engines/stark/services/settings.h
- engines/stark/services/stateprovider.h
- engines/stark/services/userinterface.cpp
- engines/stark/services/userinterface.h
- engines/stark/stark.cpp
- engines/stark/stark.h
- engines/stark/ui/menu/diaryindex.cpp
- engines/stark/ui/menu/locationscreen.cpp
- engines/stark/ui/menu/locationscreen.h
- engines/stark/ui/menu/mainmenu.cpp
- engines/stark/ui/menu/saveloadmenu.cpp
- engines/stark/ui/menu/saveloadmenu.h
- engines/stark/ui/screen.h
This PR is corresponding to implement the save & load menu of *The Longest Journey*.
> STARK: Implement the save & load menu

- engines/stark/module.mk
- engines/stark/resources/sound.cpp
- engines/stark/resources/sound.h
- engines/stark/services/diary.h
- engines/stark/services/userinterface.cpp
- engines/stark/services/userinterface.h
- engines/stark/ui/menu/diaryindex.cpp
- engines/stark/ui/menu/fmvmenu.cpp
- engines/stark/ui/menu/fmvmenu.h
- engines/stark/ui/menu/saveloadmenu.cpp
- engines/stark/ui/menu/saveloadmenu.h
- engines/stark/ui/screen.h
- engines/stark/ui/world/gamescreen.cpp
- engines/stark/ui/world/gamescreen.h
- engines/stark/visual/text.h
This PR is corresponding to the implementation of the video replay menu of TLJ, ~which is probably the easiest menu to implement~.
Based on the original game, the widget for FMV entries works slightly different from our written `StaticLocationWidget`. The cursor will not change when hovering on it. Since the widget does not have many fancy functionalities, I chose to build it out of scratch instead of extending the `StaticLocationWidget`.
I don't see the necessity to dynamically calculate some UI position parameters so I hard-coded them. If the dynamic calculation is really needed like there is a version with dramatically long video titles in a different language, it could be easily fixed.
It would be important now to actually [pause the game's sound when the menu is …
> STARK: Implement the video replay menu

- engines/stark/module.mk
- engines/stark/resources/location.cpp
- engines/stark/resources/location.h
- engines/stark/services/diary.h
- engines/stark/services/userinterface.cpp
- engines/stark/services/userinterface.h
- engines/stark/ui/menu/diaryindex.cpp
- engines/stark/ui/menu/diarypages.cpp
- engines/stark/ui/menu/diarypages.h
- engines/stark/ui/menu/locationscreen.h
- engines/stark/ui/screen.h
This PR is corresponding to implementing the diary pages menu of TLJ.
> STARK: Implement the diary pages menu

- backends/graphics/openglsdl/openglsdl-graphics.cpp
Since the internal switch to OpenGL 2.0, residualvm stopped working entirely on the AmigaOS4 platform.
Due to the fact that AmigaOS4 only supports OpenGL close to version 1.3, the program quits right after starting with an error message of not being able to create a proper screen.
This PR is to make residualvm work again on the AmigaOS4 platform (Grim Fandango is working great, EMI with a few glitches, TLJ not at all due to missing shaders).
Please revise and tell me what has to be changed to get accepted.
Maybe there is another (cleaner) way to do it, if so, please advise.
> AMIGAOS4: SDL/OGL - Add backwards compatibility for AmigaOS4

- engines/stark/console.cpp
- engines/stark/services/global.cpp
- engines/stark/services/global.h
- engines/stark/stark.h
Issue #1430 #1431 #1432 #1435 
The previous PR is merged by accident. This is a new and clean one.
> STARK: Improve the debug console

- engines/stark/console.cpp
* Changed "ids" to "indices" to unify the names in console messages about listLocations
> STARK: Updated console message to unify names

- README.md
- engines/stark/console.cpp
Changed listInventory to listInventoryItems to fit other commands, that is.:
* changeLocation → listLocations
* decompileScript, enableScript, forceScript → listScripts
so
* enableInventoryItem → listInventory**Items**
Also updated README.md with the updated command name.
> [STARK] Changed listInventory → listInventoryItems 

- engines/stark/console.cpp
- engines/stark/console.h
I accidentally forgot to change the name of the function to match, so the program won't compile now. This should be fixed with that PR, sorry!
I have to admit that I am only testing this change now (sorry again! but everything seems to work on my side now), but I'm surprised the checks went through.
> STARK: Bugfix for my previous PR

- engines/myst3/console.cpp
When using the var command in the debug console warn
if the variable number is not in range rather than
error.
> MYST3: Debug warn instead of error for unknown var

- engines/stark/resources/anim.cpp
- engines/stark/resources/anim.h
- engines/stark/resources/image.cpp
- engines/stark/resources/image.h
- engines/stark/resources/item.cpp
- engines/stark/resources/item.h
- engines/stark/resources/knowledgeset.cpp
- engines/stark/resources/knowledgeset.h
- engines/stark/resources/location.cpp
- engines/stark/resources/location.h
- engines/stark/resources/pattable.h
- engines/stark/services/diary.cpp
- engines/stark/services/gameinterface.cpp
- engines/stark/services/gameinterface.h
- engines/stark/services/staticprovider.h
- engines/stark/services/userinterface.cpp
- engines/stark/services/userinterface.h
- engines/stark/stark.cpp
- engines/stark/ui/world/clicktext.cpp
- engines/stark/ui/world/clicktext.h
- engines/stark/ui/world/dialogpanel.cpp
- engines/stark/ui/world/dialogpanel.h
- engines/stark/ui/world/gamescreen.cpp
- engines/stark/ui/world/gamescreen.h
- engines/stark/ui/world/gamewindow.cpp
- engines/stark/ui/world/gamewindow.h
- engines/stark/ui/world/inventorywindow.h
This PR is corresponding to implementing the keyboard bindings in TLJ. It is unfinished, but opened early for review and progress checking.
> STARK: Implement keyboard bindings

- engines/grim/gfx_opengl.cpp
This PR is intended to solve #1263: it ignores zero-alpha values in the color map instead of propagating them to the framebuffer causing black silhouettes to appear. I cannot reproduce the issue locally but an API trace confirmed that all pixels written have the correct alpha value now.
EDIT: this only affects the regular OpenGL drawing, and only EMI.
> GFX: Do not consult color map for alpha for AlphaOff meshes

- backends/graphics/openglsdl/openglsdl-graphics.cpp
Since the internal switch to OpenGL 2.0, residualvm stopped working entirely on the AmigaOS4 platform.
this is a followup to PR #1455
Obviously the Proile Mask must be set to "0" otherwise it will bail out again with a "Error: Invalid Window"
> AMIGAOS4: SDL/OGL - Add backwards compatibility for AmigaOS4 (followup)

- engines/stark/model/skeleton_anim.cpp
Mitigates #1436. Glitches were appearing at old lady in the forest because wasn't getting a key frame
Now, if no key frame found, defaults to last key frame with warning message.
> STARK: Set default keyframe for bone animation

- engines/grim/gfx_opengl_shaders.cpp
"swapRandB" variable must be set for sprites too, when ResidualVM is built with opengles2 + shaders support.
It fixes this kind of wrong colors rendered:
Here, flames color:
Other example, ship and blaze colors:
> GRIM: Image format must match internalformat for sprites too (ES2)

- backends/graphics/sdl/resvm-sdl-graphics.cpp
- backends/graphics/sdl/resvm-sdl-graphics.h
- backends/graphics/sdl/sdl-graphics.h
The coordinates were translated, but this was done on a copy
instead of overwriting the original object.
In ScummVM this is a reference.
Found the bug with grim-mouse fork.
> Fix mouse going out of bounds in fullscreen

- engines/grim/emi/sound/emisound.cpp
- engines/grim/emi/sound/emisound.h
Fixes #1541. Maybe #1451 too?
I reworked the load logic to just load all three known files in succession and then check if the number of valid tracks > 100. Both CD and Steam versions have 125 tracks, so 100 seems like a safe margin.
> EMI: Support merged FullMonkeyMap.int as well

- configure
Discussion welcome.
Although i´m probably not able to add anything to the reason why the decision was taken by AmigaOS4 devs on using -logles2 over -lGLESv2.
Confirmed working on AmigaOS4 (with hopefully nothing broken on any other platform).
> CONFIGURE: Add AmigaOS4 GLESv2 implementation

- engines/grim/gfx_opengl.cpp
GL_UNSIGNED_INT_8_8_8_8 is not (yet) recognized as a format.
Fixes #1498
> AMIGAOS4: Use GL_UNSIGNED_BYTE for uploading video frames

- engines/grim/textsplit.cpp
These changes fix issues with a minor impact because they are revealed at exit.
But that cleans the code and avoid pollution, what will ease the detection of other problems.
Problems were found thanks to compilation code instrumentation (using sanitizers).
> GRIM: Fix alloc-dealloc mismatch in grim engine

- engines/grim/emi/sound/emisound.cpp
After having installed EMI data and started the game, if we are in the situation
where it is asked to rename resource file FullMonkeyMap.imt from both CDs
into FullMonkeyMap1.imt and FullMonkeyMap2.imt, the game tries to start but
leads to an immediate segmentation fault.
In EMISound::setMusicState, _musicTable is checked againt nullptr but ... after
it is used. This check is moved up.
> EMI: Check _musicTable is null before it is used to avoid segfault

- engines/grim/gfx_opengl.cpp
- engines/grim/gfx_opengl_shaders.cpp
In EMI and GRIM games, a resource leak was found with OpenGL and
OpenGL-shaders engines: releaseMovieFrame() was not called in the destructor
of these graphics drivers (and never called at all on exit).
This patch calls explicitely realeaseMovieFrame.
Note that is was already done correctly with TinyGL.
> GRIM: Fix resource leak calling releaseMovieFrame

- graphics/tinygl/zdirtyrect.cpp
The function end() of a list does not return the last element but a fake element
after the last one, for the need of the iterator.
Trying to access to the data of the element returned by end() and that has no
such field, that caused a stack buffer overflow, reading uninitialized data.
Called function back() instead, to get the last element of the list.
> TINYGL: Fix wrong access to the list of dirty rects

- engines/stark/console.cpp
The 'Too few args' message should only be
displayed if some but not enough arguments
are provided. Otherwise just show the
instructions of the command.
Refs #1464
> STARK: Make debug command output more consistent

- .travis/android-build
- .travis/android-set-environment
- backends/platform/android/android.cpp
- backends/platform/android/android.mk
- configure
The first commit fixes some build issues I encountered while building Android on macOS.
The second commit fixes #1589. It also _always_ resets the lastpath.
> ANDROID: always start browser on external storage (SD card)

- backends/graphics/sdl/resvm-sdl-graphics.cpp
- backends/graphics/sdl/resvm-sdl-graphics.h
- backends/platform/sdl/sdl-window.cpp
- backends/platform/sdl/sdl-window.h
- backends/platform/sdl/sdl.cpp
- backends/platform/sdl/sdl.h
Reverts residualvm/residualvm#1622  no reason to change
> Revert "SDL: Move detection of the desktop resolution into the SdlWindow class"

- engines/grim/emi/lua_v2.cpp
- engines/grim/grim.cpp
- engines/grim/grim.h
- engines/grim/movie/bink.cpp
- engines/grim/movie/movie.cpp
- engines/grim/movie/movie.h
This fixes #1161.
In the course of implementing this, I stumbled upon a race condition in the subtitle drawing:
- the movie thread takes the frame mutex to update its internal structures and update `_movieSubtitle`.
- the drawing thread only takes the mutex (briefly) to grab any new movie frames, but does not synchronize to take the subtitle.
I fixed this by drawing the subtitles while holding the movie mutex. It works but I'm open to nicer suggestions. I tried to see if we could only take a _copy_ of the `TextObject::Ptr` while holding the mutex, but the movie player calls `delete` on the underlying pointer, and a `TextObject::Ptr` is not a proper smart pointer...
> EMI: Always enable movie subtitles for the demo

- backends/platform/sdl/amigaos/amigaos.mk
There´s a catch unfortunately.
As one can, see there are two files automatically installed (icons for drawer and app), but i´m not allowed to upload those through the GitHub site.
So, i´d need help with that, please.
Could some dev please grab the attached files and place them into "dists/amiga/"?
Thanks a lot
[residualvm.zip](https://github.com/residualvm/residualvm/files/4688502/residualvm.zip)
> AMIGAOS4: Automate installation process on local builds

- backends/platform/android/events.cpp
- backends/platform/android/graphics.cpp
Myst III on Android can be started and played till some point after these changes. Tested on x86 and armv7.
> ANDROID: Fix sigsegv and sigfpe on start. Enable basic touch control.

- engines/icb/res_man.h
- engines/icb/res_man_pc.cpp
See also scummvm/scummvm#2416. These changes have not been tested.
> ICB: Remove direct use of OSystem::createMutex()

- engines/grim/detection.cpp
- engines/grim/detection.h
- engines/grim/grim.h
- engines/grim/metaengine.cpp
- engines/icb/detection.cpp
- engines/icb/metaengine.cpp
- engines/myst3/database.h
- engines/myst3/detection.cpp
- engines/myst3/detection.h
- engines/myst3/metaengine.cpp
- engines/stark/detection.cpp
- engines/stark/metaengine.cpp
Please refer to https://github.com/scummvm/scummvm/pull/2403 to refer to the main changes.
This PR adds support for each of ResidualVM's engines to the new split of MetaEngines, and enables detection features to be linked statically.
PS: This is only meant to be merged once ScummVM's PR is merged and when ResidualVM chooses to sync with ScummVM.
> ENGINES: ALL: Split detection features (Individual engines support) [DO NOT MERGE]
